# ------------------------------------------------------------------------------
# Makefile — Lab 13: Terraform -> Ansible Integration.
#
# Standard targets: setup, lint, test, deploy, destroy, clean.
# Lab-specific targets:
#   all   terraform apply, then run the Ansible playbook (the full handoff)
#   ping  check SSH connectivity to the hosts in the generated inventory
#
# Usage (from the repo root of this lab branch):
#   make setup     # verify tools and prerequisites
#   make all       # build infra + configure it end to end
#   make destroy   # tear the cloud resources down
#
# The SSH private key defaults to ~/.ssh/id_rsa; override with:
#   make all KEY=~/.ssh/lab13-key.pem
# ------------------------------------------------------------------------------

TF_DIR        := terraform
INV_FILE      := ansible/inventory/aws_hosts.ini
PLAYBOOK      := ansible/site.yml
KEY           ?= ~/.ssh/id_rsa

.PHONY: help setup lint test deploy destroy clean all ping

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-10s\033[0m %s\n", $$1, $$2}'

setup: ## Verify required tools and AWS credentials
	@echo "Checking required tools..."
	@command -v terraform >/dev/null || { echo "ERROR: terraform not found. See the README."; exit 1; }
	@command -v ansible-playbook >/dev/null || { echo "ERROR: ansible not found. See the README."; exit 1; }
	@command -v aws >/dev/null || echo "WARN: aws CLI not found (optional — only needed to create the key pair)"
	@if [ -z "$$AWS_ACCESS_KEY_ID" ] && [ ! -f "$$HOME/.aws/credentials" ]; then \
		echo "WARN: no AWS credentials detected (AWS_ACCESS_KEY_ID env var or ~/.aws/credentials)."; \
		echo "      terraform apply will fail until you configure them."; \
	else \
		echo "AWS credentials detected."; \
	fi
	@terraform version
	@ansible --version | head -n 1
	@echo "Setup OK. Next: cp $(TF_DIR)/terraform.tfvars.example $(TF_DIR)/terraform.tfvars and edit it."

lint: ## Run terraform fmt/validate and ansible-lint
	@echo "Running terraform fmt check..."
	terraform -chdir=$(TF_DIR) fmt -check
	@echo "Running terraform validate..."
	terraform -chdir=$(TF_DIR) init -backend=false >/dev/null
	terraform -chdir=$(TF_DIR) validate
	@echo "Running ansible-lint..."
	@command -v ansible-lint >/dev/null || { echo "WARN: ansible-lint not installed; skipping."; exit 0; }
	ansible-lint $(PLAYBOOK)
	@echo "Lint OK."

test: ## No unit tests in this lab — validate the Terraform config instead
	@echo "No unit tests in this lab (see Lab 12 for Molecule role testing)."
	@echo "Running terraform validate as a sanity check..."
	terraform -chdir=$(TF_DIR) init -backend=false >/dev/null
	terraform -chdir=$(TF_DIR) validate
	@echo "Test OK."

deploy: ## Terraform flow only: init -> plan -> apply (generates the inventory)
	terraform -chdir=$(TF_DIR) init
	terraform -chdir=$(TF_DIR) plan -out=tfplan
	terraform -chdir=$(TF_DIR) apply tfplan
	@echo "Deploy complete. Inventory written to $(INV_FILE):" && cat $(INV_FILE)

all: deploy ## Full handoff: terraform apply, then the Ansible playbook
	@test -f $(INV_FILE) || { \
		echo "ERROR: $(INV_FILE) not found."; \
		echo "       It should have been generated by 'terraform apply'. Did apply succeed?"; \
		exit 1; \
	}
	@echo "Inventory found. Running Ansible playbook against it..."
	ansible-playbook -i $(INV_FILE) $(PLAYBOOK) -u ubuntu --private-key $(KEY)
	@echo "All done. Try: curl http://$$(terraform -chdir=$(TF_DIR) output -raw web_public_ip)"

ping: ## Check SSH connectivity to hosts in the generated inventory
	@test -f $(INV_FILE) || { \
		echo "ERROR: $(INV_FILE) not found. Run 'make deploy' first."; \
		exit 1; \
	}
	ansible -i $(INV_FILE) webservers -m ansible.builtin.ping -u ubuntu --private-key $(KEY)

destroy: ## Tear down all AWS resources (the generated inventory is removed too)
	terraform -chdir=$(TF_DIR) destroy
	@echo "Destroy complete. NOTE: terraform destroy also removes $(INV_FILE)"
	@echo "(it is a Terraform-managed resource). It is re-created on every apply."

clean: ## Remove local build artifacts (keeps tfvars; state is removed only on request)
	rm -rf $(TF_DIR)/.terraform
	rm -f $(TF_DIR)/.terraform.lock.hcl $(TF_DIR)/tfplan $(TF_DIR)/crash.log
	@echo "Cleaned Terraform working files. terraform.tfvars and *.tfstate* were kept."
	@echo "The generated $(INV_FILE) is managed by Terraform and was NOT deleted here."
