# inventory.tf — Lab 13 behavior carried into the capstone: after each apply,
# Terraform renders a static inventory file for Ansible. The CI pipeline
# actually uses the *dynamic* aws_ec2 plugin inventory; this generated file is
# uploaded as a build artifact and serves as a local debugging fallback.

locals {
  # Shared per-host SSH options for the generated static inventory.
  ssh_opts = "ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa"
}

resource "local_file" "ansible_inventory" {
  filename        = "${path.module}/../ansible/inventory/hosts.ini"
  file_permission = "0644"

  # <<-EOT strips the leading indentation so the rendered file is clean INI.
  content = <<-EOT
    # Generated by Terraform from lab-17-full-devops-pipeline. DO NOT EDIT.
    # Fallback inventory only — the pipeline uses inventory/aws_ec2.yml.
    [web]
    ${aws_instance.web.public_ip} ${local.ssh_opts}
  EOT
}
