# ------------------------------------------------------------------------------
# main.tf — the infrastructure + the Terraform -> Ansible handoff.
#
# This file does two jobs:
#   1. Builds a minimal free-tier AWS web stack: VPC, public subnet, security
#      group, and a single t2.micro Ubuntu EC2 instance.
#   2. Performs the HANDOFF to Ansible: a `local_file` resource renders a
#      static Ansible inventory (../ansible/inventory/aws_hosts.ini) containing
#      the instance's public IP. After `terraform apply`, Ansible reads that
#      file and configures the host — no IPs are ever copied by hand.
#
# Run order: terraform init -> terraform apply -> inspect the generated
# inventory -> ansible-playbook (see README.md).
# ------------------------------------------------------------------------------

# --- Latest Ubuntu 22.04 LTS AMI (free-tier friendly) -------------------------
# A data source looks up the newest official Ubuntu image at apply time, so the
# lab keeps working as AMIs are replaced.
data "aws_ami" "ubuntu" {
  most_recent = true
  owners      = ["099720109477"] # Canonical

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# --- Networking ---------------------------------------------------------------
resource "aws_vpc" "main" {
  cidr_block           = "10.13.0.0/16"
  enable_dns_hostnames = true

  tags = {
    Name = "${var.project_name}-vpc"
  }
}

resource "aws_internet_gateway" "main" {
  vpc_id = aws_vpc.main.id

  tags = {
    Name = "${var.project_name}-igw"
  }
}

resource "aws_subnet" "public" {
  vpc_id                  = aws_vpc.main.id
  cidr_block              = "10.13.1.0/24"
  map_public_ip_on_launch = true # instances get a public IP automatically

  tags = {
    Name = "${var.project_name}-subnet"
  }
}

# Route all outbound traffic through the internet gateway.
resource "aws_route_table" "public" {
  vpc_id = aws_vpc.main.id

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.main.id
  }

  tags = {
    Name = "${var.project_name}-rt"
  }
}

resource "aws_route_table_association" "public" {
  subnet_id      = aws_subnet.public.id
  route_table_id = aws_route_table.public.id
}

# --- Security group ------------------------------------------------------------
# SSH (22) so Ansible can connect, HTTP (80) so we can curl the Nginx page.
resource "aws_security_group" "web" {
  name        = "${var.project_name}-sg"
  description = "Allow SSH from var.ssh_allowed_cidr and HTTP from anywhere"
  vpc_id      = aws_vpc.main.id

  ingress {
    description = "SSH for Ansible configuration"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [var.ssh_allowed_cidr]
  }

  ingress {
    description = "HTTP for the Nginx welcome page"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    description = "Allow all outbound (apt updates, packages, metadata)"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "${var.project_name}-sg"
  }
}

# --- EC2 instance ---------------------------------------------------------------
# user_data only prepares the machine for Ansible (installs python3, which
# Ansible needs on the target). Nginx itself is installed by Ansible — that is
# the whole point of the handoff: Terraform builds, Ansible configures.
resource "aws_instance" "web" {
  ami                         = data.aws_ami.ubuntu.id
  instance_type               = var.instance_type
  subnet_id                   = aws_subnet.public.id
  vpc_security_group_ids      = [aws_security_group.web.id]
  key_name                    = var.key_name
  associate_public_ip_address = true

  user_data = <<-EOT
    #!/bin/bash
    # Make sure python3 is present — Ansible requires it on managed hosts.
    apt-get update
    apt-get install -y python3
  EOT

  tags = {
    Name = "${var.project_name}-web"
  }
}

# --- THE HANDOFF: render the Ansible inventory ---------------------------------
# local_file writes a file on the machine running Terraform. Here it renders a
# ready-to-use static inventory with the EC2 public IP injected. Because it is
# a Terraform resource, the inventory is refreshed automatically on every
# apply — if the IP changes, the file is updated (never edit it by hand;
# Terraform will just overwrite your changes on the next apply).
resource "local_file" "ansible_inventory" {
  filename        = "${path.module}/../ansible/inventory/aws_hosts.ini"
  file_permission = "0644"

  content = <<-EOT
    # ---------------------------------------------------------------------------
    # GENERATED BY TERRAFORM — do not edit by hand.
    # Created by the local_file.ansible_inventory resource in terraform/main.tf.
    # This file is re-written on every `terraform apply`, so any manual edits
    # will be lost. Terraform also deletes it on `terraform destroy`.
    # ---------------------------------------------------------------------------

    [webservers]
    ${aws_instance.web.public_ip} ansible_user=ubuntu

    [webservers:vars]
    # Point this at the private key matching the AWS key pair (var.key_name).
    # The lab instead passes --private-key on the ansible-playbook command line;
    # uncomment the line below if you prefer to keep it in the inventory:
    # ansible_ssh_private_key_file = ~/.ssh/id_rsa
    ansible_ssh_common_args = -o StrictHostKeyChecking=accept-new
  EOT
}
