# ------------------------------------------------------------------------------
# outputs.tf — values printed after `terraform apply`.
#
# These make the verification steps copy-paste friendly: the public IP, the
# path of the generated inventory, and ready-made curl/ssh commands.
# ------------------------------------------------------------------------------

output "web_public_ip" {
  description = "Public IP of the EC2 instance. Also embedded in the generated Ansible inventory."
  value       = aws_instance.web.public_ip
}

output "web_public_dns" {
  description = "Public DNS name of the EC2 instance."
  value       = aws_instance.web.public_dns
}

output "inventory_file" {
  description = "Path of the Ansible inventory generated by Terraform (the handoff artifact)."
  value       = local_file.ansible_inventory.filename
}

output "curl_check_command" {
  description = "Command to verify Nginx after the playbook runs."
  value       = "curl http://${aws_instance.web.public_ip}"
}

output "ssh_motd_command" {
  description = "Command to SSH in and see the custom MOTD Ansible deployed."
  value       = "ssh -i ~/.ssh/id_rsa ubuntu@${aws_instance.web.public_ip}"
}
